#!/usr/bin/python3

# GR2G - - Grains to Grams conversion

# USEAGE -- $gr2g [grams]

from sys import argv
script,conv_grains=argv
conv_grains=float(conv_grains)
convd_grams=conv_grains * 0.06479891
print("\n\t%s grians == %s grams\n\n" % (conv_grains, convd_grams))
